on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go-version}}
    - name: checkout
      uses: actions/checkout@v2
    - name: gofmt
      run: test -z "`gofmt -l .`"
    - name: golint
      run: test -z "`golint ./...`"
    - name: go-test
      run: go test -v ./...
    - name: run example
      run: cd example && go build -o http_breaker && ./http_breaker
